name: Build, Test, and Generate SBOM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    - run: dotnet restore build/build.csproj

    - run: dotnet build --no-restore build/build.csproj

    - run: dotnet test build/build.csproj

    - name: Install CycloneDX CLI
      run: |
        VERSION=0.27.1  # Update as needed
        DOWNLOAD_URL="https://github.com/CycloneDX/cyclonedx-cli/archive/refs/tags/v$VERSION.zip"

        echo "Downloading CycloneDX CLI from $DOWNLOAD_URL"
        
        curl -sL "$DOWNLOAD_URL" -o cyclonedx-cli.zip
        unzip cyclonedx-cli.zip -d cyclonedx-cli-source
        cd cyclonedx-cli-source/cyclonedx-cli-$VERSION/src/cyclonedx

        # Build the CycloneDX CLI tool as a native executable
        dotnet publish cyclonedx.csproj -c Release -r linux-x64 --self-contained -o ./output

        # Check the contents of the output directory
        ls -la ./output

        # Ensure that the cyclonedx binary is executable and move it to /usr/local/bin
        sudo mv ./output/cyclonedx /usr/local/bin/cyclonedx
        sudo chmod +x /usr/local/bin/cyclonedx

    - name: Verify CycloneDX CLI Installation
      run: |
        cyclonedx --version

    - name: Generate SBOM
      run: |
        cyclonedx -o sbom.xml

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SBOM
        path: sbom.xml
