name: Build, Test, and Generate SBOM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    - run: dotnet restore build/build.csproj
    - run: dotnet build --no-restore build/build.csproj
    - run: dotnet publish build/build.csproj -c Release -o build/output

    - run: dotnet test build/build.csproj

    - name: Install CycloneDX CLI
      run: dotnet tool install --global CycloneDX

    - name: Generate SBOM
      run: |
        dotnet CycloneDX -j Conduit.sln -o sbom.json

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SBOM
        path: sbom.json
