name: Build, Test, and Generate SBOM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - uses: actions/checkout@v4

    # Set up the .NET environment
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    # Restore dependencies
    - run: dotnet restore build/build.csproj

    # Build the project
    - run: dotnet build --no-restore build/build.csproj

    # Run tests (optional, if you have tests in the project)
    - run: dotnet test build/build.csproj

    # Download and Install CycloneDX CLI from .deb file
    - name: Install CycloneDX CLI
      run: |
        VERSION=0.27.1  # Replace with the desired version of CycloneDX CLI
        DOWNLOAD_URL="https://github.com/CycloneDX/cyclonedx-cli/releases/download/v$VERSION/cyclonedx-cli-$VERSION-linux-x64.deb"

        # Print the download URL
        echo "Downloading CycloneDX CLI from $DOWNLOAD_URL"

        # Check if the download URL is valid
        http_response=$(curl --write-out "%{http_code}" --silent --output /dev/null "$DOWNLOAD_URL")
        if [ "$http_response" -ne 200 ]; then
          echo "Error: Failed to download the file. HTTP response code: $http_response"
          exit 1
        fi

        # Download the .deb package
        curl -sL "$DOWNLOAD_URL" -o cyclonedx-cli.deb

        # Install the .deb package
        sudo dpkg -i cyclonedx-cli.deb
        
        # Install dependencies if dpkg reports any issues
        sudo apt-get install -f

    # Generate the SBOM
    - name: Generate SBOM
      run: |
        cyclonedx -o sbom.xml

    # Optionally, upload the SBOM as an artifact
    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v3
      with:
        name: SBOM
        path: sbom.xml
