name: Build, Test, and Generate SBOM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    - run: dotnet restore build/build.csproj

    - run: dotnet publish --configuration Release --output ./build/output build/build.csproj

    - run: dotnet test build/build.csproj

    - name: Install CycloneDX CLI
      run: |
        VERSION=0.27.1
        DOWNLOAD_URL="https://github.com/CycloneDX/cyclonedx-cli/releases/download/v$VERSION/cyclonedx-linux-x64"
        curl -sL "$DOWNLOAD_URL" -o cyclonedx
        sudo chmod +x cyclonedx
        sudo mv cyclonedx /usr/local/bin/cyclonedx

    - name: Verify CycloneDX CLI Installation
      run: |
        cyclonedx --version

    - name: Check build output directory
      run: |
        echo "Listing files in the build output directory"
        ls -R build/

    - name: Ensure correct paths
      run: |
        if [ ! -f "build/output/myapp.dll" ]; then
          echo "myapp.dll not found in build/output/"
          echo "Listing files in build/output"
          ls -R build/output
          exit 1
        fi

    - name: Generate SBOM
      run: |
        cyclonedx convert --input-file ./build/output/myapp.dll --output-file sbom.xml --input-format auto --output-format xml

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SBOM
        path: sbom.xml
