name: Build, Test, and Generate SBOM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - uses: actions/checkout@v4

    # Set up the .NET environment
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    # Restore dependencies
    - run: dotnet restore build/build.csproj

    # Build the project
    - run: dotnet build --no-restore build/build.csproj

    # Run tests (optional, if you have tests in the project)
    - run: dotnet test build/build.csproj

    # Download and install CycloneDX CLI from the source .zip file
    - name: Install CycloneDX CLI
      run: |
        VERSION=0.27.1  # Update if needed
        DOWNLOAD_URL="https://github.com/CycloneDX/cyclonedx-cli/archive/refs/tags/v$VERSION.zip"

        # Print the download URL
        echo "Downloading CycloneDX CLI from $DOWNLOAD_URL"

        # Download the .zip file containing the source
        curl -sL "$DOWNLOAD_URL" -o cyclonedx-cli.zip

        # Extract the source code
        unzip cyclonedx-cli.zip -d cyclonedx-cli-source

        # Navigate to the extracted directory and build the CLI tool
        cd cyclonedx-cli-source/cyclonedx-cli-$VERSION
        dotnet publish -c Release -o ./output

        # Move the CLI tool binary to a directory in PATH
        sudo mv ./output/cyclonedx-cli /usr/local/bin/cyclonedx-cli
        sudo chmod +x /usr/local/bin/cyclonedx-cli

    # Generate the SBOM
    - name: Generate SBOM
      run: |
        cyclonedx-cli -o sbom.xml

    # Optionally, upload the SBOM as an artifact
    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v3
      with:
        name: SBOM
        path: sbom.xml
