name: Build, Test, and Generate SBOM

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - uses: actions/checkout@v4

    # Set up the .NET environment
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    # Restore dependencies
    - run: dotnet restore build/build.csproj

    # Build the project
    - run: dotnet build --no-restore build/build.csproj

    # Run tests (optional, if you have tests in the project)
    - run: dotnet test build/build.csproj

    # Download and Install CycloneDX CLI - specify a stable version
    - name: Install CycloneDX CLI
      run: |
        VERSION=0.27.1
        DOWNLOAD_URL="https://github.com/CycloneDX/cyclonedx-cli/releases/download/v$VERSION/cyclonedx-linux-x64.tar.gz"
        
        # Download CycloneDX CLI
        echo "Downloading CycloneDX CLI from $DOWNLOAD_URL"
        curl -sL "$DOWNLOAD_URL" -o cyclonedx.tar.gz
        
        # Verify that the file was downloaded correctly
        if ! file cyclonedx.tar.gz | grep -q 'gzip compressed data'; then
          echo "Error: Downloaded file is not in gzip format. Exiting."
          exit 1
        fi
        
        # Extract and move the binary
        tar -xzf cyclonedx.tar.gz
        sudo mv cyclonedx /usr/local/bin/

    # Generate the SBOM
    - name: Generate SBOM
      run: |
        cyclonedx -o sbom.xml

    # Optionally, upload the SBOM as an artifact
    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v3
      with:
        name: SBOM
        path: sbom.xml
