name: Build, Test, and Generate SBOM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    - run: dotnet restore build/build.csproj

    - run: dotnet build --no-restore build/build.csproj

    - run: dotnet test build/build.csproj

    - name: Install CycloneDX CLI
      run: |
        VERSION=0.27.1  # Replace with the desired version
        DOWNLOAD_URL="https://github.com/CycloneDX/cyclonedx-cli/releases/download/v$VERSION/cyclonedx-linux-x64"

        # Download the CycloneDX CLI binary
        curl -sL "$DOWNLOAD_URL" -o cyclonedx

        # Make the binary executable
        sudo chmod +x cyclonedx

        # Move the cyclonedx binary to /usr/local/bin
        sudo mv cyclonedx /usr/local/bin/cyclonedx

    - name: Verify CycloneDX CLI Installation
      run: |
        cyclonedx --version

    - name: Check if DLL exists
      run: |
        if [ ! -f "build/bin/Release/net6.0/myapp.dll" ]; then
          echo "Error: myapp.dll not found in build/bin/Release/net6.0/"
          exit 1
        fi

    - name: Generate SBOM
      run: |
        # Generate the SBOM using the correct command for CycloneDX
        cyclonedx convert --input-file build/bin/Release/net6.0/myapp.dll --output-file sbom.xml --input-format json --output-format json

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SBOM
        path: sbom.xml
