name: Build, Test, and Generate SBOM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    - run: dotnet restore build/build.csproj
    - run: dotnet build --no-restore build/build.csproj
    - run: dotnet publish build/build.csproj -c Release -o build/output

    - run: dotnet test build/build.csproj

    - name: Install CycloneDX CLI for .NET
      run: dotnet tool install --global CycloneDX.Cli

    - name: Generate SBOM
      env:
        PATH: $PATH:/home/runner/.dotnet/tools  # Add dotnet tools to the PATH
      run: |
        cyclonedx-cli sbom --project-name "MyApp" --output-format xml --output-file sbom.xml --include-project-references --output-version v1_4

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SBOM
        path: sbom.xml
