name: Build, Test, and Generate SBOM

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    - run: dotnet restore build/build.csproj
    - run: dotnet build --no-restore build/build.csproj
    - run: dotnet publish build/build.csproj -c Release -o build/output

    - run: dotnet test build/build.csproj

    - name: Install CycloneDX CLI (from GitHub releases)
      run: |
        VERSION=0.27.1  # Use the desired version
        DOWNLOAD_URL="https://github.com/CycloneDX/cyclonedx-cli/releases/download/v$VERSION/cyclonedx-linux-x64"
        
        echo "Downloading CycloneDX CLI from $DOWNLOAD_URL"
        curl -sL "$DOWNLOAD_URL" -o cyclonedx
        
        chmod +x cyclonedx
        sudo mv cyclonedx /usr/local/bin/cyclonedx

    - name: Generate SBOM
      run: |
        dotnet cyclonedx -j Conduit.sln -o sbom.json

    - name: Upload SBOM Artifact
      uses: actions/upload-artifact@v3
      with:
        name: SBOM
        path: sbom.json
