name: Build, Test, and Generate SBOM

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - uses: actions/checkout@v4

    # Set up the .NET environment
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    # Restore dependencies
    - run: dotnet restore build/build.csproj

    # Build the project
    - run: dotnet build --no-restore build/build.csproj

    # Run tests (optional, if you have tests in the project)
    - run: dotnet test build/build.csproj

    # Generate the SBOM using CycloneDX GitHub Action
    - name: Generate SBOM
      uses: CycloneDX/gh-cyclonedx-action@v1
      with:
        output-format: xml
        output-file: sbom.xml

    # Optionally, upload the SBOM as an artifact
    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v3
      with:
        name: SBOM
        path: sbom.xml
