name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.204
      - run: dotnet run --project build/build.csproj

  test:
    name: Tests for .NET Core ${{ matrix.framework }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        framework: ['net6.0', 'net7.0', 'net8.0']
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.framework }}
      - name: Run Tests
        run: dotnet test --framework ${{ matrix.framework }} --collect:"XPlat Code Coverage;Format=cobertura" --results-directory "TestResults"
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@v5
        with:
          reports: 'TestResults/**/coverage.cobertura.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline;Cobertura;MarkdownSummaryGithub'
      # Optional: Add PR Comment
      # - name: Add Coverage PR Comment
      #   uses: marocchino/sticky-pull-request-comment@v2
      #   if: github.event_name == 'pull_request'
      #   with:
      #     recreate: true
      #     path: ./coveragereport/SummaryGithub.md
      - name: Write to Job Summary
        run: cat ./coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY
        shell: bash
      - name: Upload Coverage Report Artifact
        if: ${{ matrix.os == 'ubuntu-latest' && matrix.framework == 'net8.0' }}
        uses: actions/upload-artifact@v4
        with:
          name: CoverageReport_${{ matrix.framework }}_${{ matrix.os }}
          path: coveragereport
