name: Build, Test, and Generate SBOM

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    # Check out the repository code
    - uses: actions/checkout@v4

    # Set up the .NET environment
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.204

    # Restore dependencies
    - run: dotnet restore build/build.csproj

    # Build the project
    - run: dotnet build --no-restore build/build.csproj

    # Run tests (optional, if you have tests in the project)
    - run: dotnet test build/build.csproj

    # Install CycloneDX CLI for .NET
    - name: Install CycloneDX CLI
      run: |
        dotnet tool install --global CycloneDX.Cli

      env:
        PATH: ${{ github.env }}:/home/runner/.dotnet/tools

    # Generate the SBOM
    - name: Generate SBOM
      run: |
        cyclonedx -o sbom.xml

    # Optionally, upload the SBOM as an artifact
    - name: Upload SBOM artifact
      uses: actions/upload-artifact@v3
      with:
        name: SBOM
        path: sbom.xml
